name: Build APK Android Baru

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v4
        
      - name: Siapkan Mesin Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Siapkan Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Semua Kebutuhan
        run: |
          python -m pip install --upgrade pip
          pip install flet==0.25.2 pandas openpyxl
          
      - name: Rakit Menjadi APK (Otomatis)
        run: yes | flet build apk
        
      - name: Simpan File APK
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-ShinePerabot-Final
          path: build/apk/**/*.apk
